### ISSUE TITLE
qemu vnc tablet issues

### ISSUE THREAD

**Issue by logan71f100** [kanjitalk755/macos9-usb-tablet#3]
I use vnc to access my qemu and when I first installed it worked exactly as intended. After a reboot it didn't work even though it is in the start up folder. After rebooting several more times it then worked...not really sure what's going on why its inconsistent across reboots. Any ideas? I don't know how to get logs from qemu and a quick google was not very helpful. 

my qemu is windows 5.2 and I'm running os9.2

my bug report for similar issue but I don't think has anything to do with you maybe, I really don't know lol
[https://gitlab.com/qemu-project/qemu/-/issues/595](url)

This bug is worth a 100 bucks to me if it can be squashed

**Comment by logan71f100** [comment]
side note I disabled vnc and the issue still persists even through gui hmmmmmmmmmmmmm

**Comment by kanjitalk755** [comment]
Paste the arguments when you ran QEMU.

**Comment by logan71f100** [comment]
qemu-system-ppc.exe -L pc-bios -boot c -M mac99,accel=tcg,via=pmu -m 256 ^
-prom-env "auto-boot?=true" -prom-env "boot-args=-v" -prom-env "vga-ndrv?=true" -vnc :1 ^
-drive file=MacOS9.2.img,format=raw,media=disk ^
-device usb-tablet -rtc base=localtime ^
-netdev tap,id=network01,ifname=tap-bridge1 -device sungem,netdev=network01,mac=52:54:00:12:34:56 ^
-device VGA,edid=on ^
-g 1024x768x32 

thats what im using on my windows host atm

**Comment by logan71f100** [comment]
I could send you a google drive link of the whole vm, its only 256 mbs once compressed

**Comment by kanjitalk755** [comment]
Try removing `,via=pmu`.

**Comment by logan71f100** [comment]
so far that seems to have done it! something so simple but now I see how that could have affected this. What's your PayPal? haha

**Comment by kanjitalk755** [comment]
It's free :)
